version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
  open-pull-requests-limit: 10
  target-branch: develop
  reviewers:
  - bkimminich
  labels:
  - dependencies
  ignore:
  - dependency-name: express-jwt
    versions:
    - 0.1.3
  - dependency-name: jsonwebtoken
    versions:
    - 0.4.0
  - dependency-name: sanitize-html
    versions:
    - 1.4.2
  - dependency-name: unzipper
    versions:
    - 0.9.15
  - dependency-name: sinon
    versions:
    - 10.0.0
    - 9.2.4
  - dependency-name: sequelize
    versions:
    - 6.5.0
    - 6.5.1
    - 6.6.0
    - 6.6.1
  - dependency-name: sanitize-html
    versions:
    - 2.3.2
  - dependency-name: file-type
    versions:
    - 16.2.0
- package-ecosystem: npm
  directory: "/frontend"
  schedule:
    interval: daily
    time: "09:00"
  open-pull-requests-limit: 10
  target-branch: develop
  reviewers:
  - bkimminich
  labels:
  - dependencies
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.23
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.27
    - 14.14.28
    - 14.14.29
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: rxjs
    versions:
    - 6.6.3
    - 6.6.4
    - 6.6.6
    - 6.6.7
  - dependency-name: ngx-spinner
    versions:
    - 10.0.1
    - 11.0.0
  - dependency-name: karma
    versions:
    - 6.0.3
    - 6.0.4
    - 6.1.0
    - 6.1.1
    - 6.1.2
    - 6.2.0
    - 6.3.0
    - 6.3.1
  - dependency-name: jasmine-core
    versions:
    - 3.6.0
    - 3.7.0
  - dependency-name: "@nguniversal/express-engine"
    versions:
    - 11.1.1
    - 11.1.2
    - 11.2.0
  - dependency-name: ng-mat-search-bar
    versions:
    - 9.0.1
